# Fixed Prometheus Configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# Load rules once and periodically evaluate them
# rule_files:
#   - "rules/*.yml"

# Scrape configurations - Fixed targets and endpoints
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Node Exporter - System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # cAdvisor - Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s

  # Backend application metrics
  - job_name: 'devsecops-backend'
    static_configs:
      - targets: ['backend:5000']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # PostgreSQL Exporter - Fixed
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 15s

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Jaeger metrics
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # NGINX Exporter
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 15s

  # Elasticsearch metrics - Fixed endpoint
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: '/_prometheus/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Kibana metrics - Fixed endpoint  
  - job_name: 'kibana'
    static_configs:
      - targets: ['kibana:5601']
    metrics_path: '/api/stats'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Note: Removed docker and logstash targets as they require special configuration
  # Docker daemon metrics require Docker daemon to be configured with --experimental=true
  # and metrics-addr set to 0.0.0.0:9323
  
  # Logstash metrics endpoint needs to be properly configured in logstash.yml
  # - job_name: 'logstash'
  #   static_configs:
  #     - targets: ['logstash:9600']
  #   metrics_path: '/_node/stats'
  #   scrape_interval: 30s
