# Prometheus Configuration for DevSecOps with ELK & Jaeger
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

  # External labels for federation and alerting
  external_labels:
    cluster: 'devsecops-cluster'
    environment: 'development'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Rule files
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics

  # DevSecOps Backend API
  - job_name: 'devsecops-backend'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ['backend:5000']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'devsecops-backend'

  # DevSecOps Frontend (if it exposes metrics)
  - job_name: 'devsecops-frontend'
    scrape_interval: 30s
    static_configs:
      - targets: ['frontend:80']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'devsecops-frontend'

  # Elasticsearch metrics
  - job_name: 'elasticsearch'
    scrape_interval: 30s
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: /_prometheus/metrics
    scrape_timeout: 10s

  # Elasticsearch Exporter (if deployed)
  - job_name: 'elasticsearch-exporter'
    scrape_interval: 30s
    static_configs:
      - targets: ['elasticsearch-exporter:9114']
    metrics_path: /metrics

  # Logstash metrics
  - job_name: 'logstash'
    scrape_interval: 30s
    static_configs:
      - targets: ['logstash:9600']
    metrics_path: /_node/stats
    params:
      format: ['prometheus']

  # Kibana metrics (if available)
  - job_name: 'kibana'
    scrape_interval: 30s
    static_configs:
      - targets: ['kibana:5601']
    metrics_path: /api/status
    scrape_timeout: 10s

  # Jaeger metrics
  - job_name: 'jaeger'
    scrape_interval: 30s
    static_configs:
      - targets: ['jaeger:14269']
    metrics_path: /metrics

  # PostgreSQL metrics (requires postgres_exporter)
  - job_name: 'postgres'
    scrape_interval: 30s
    static_configs:
      - targets: ['postgres-exporter:9187']
    metrics_path: /metrics

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    scrape_interval: 30s
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    scrape_interval: 30s
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: /metrics

# Remote write configuration for long-term storage (optional)
# remote_write:
#   - url: "http://remote-storage:9201/receive"
#     queue_config:
#       max_samples_per_send: 10000
#       max_shards: 100

# Remote read configuration (optional)
# remote_read:
#   - url: "http://remote-storage:9201/read"
