apiVersion: '1' # FIXED: String value

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    jsonData: # FIXED: Only valid fields
      httpMethod: POST
      manageAlerts: true
      queryTimeout: "60s"
    editable: true

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    basicAuth: false
    jsonData: # FIXED: Removed invalid tracesToLogs block
      nodeGraph:
        enabled: true
    uid: jaeger-ds
    editable: true

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    basicAuth: true # FIXED: Assume security is on
    jsonData: # FIXED: Valid fields and values
      esVersion: 8.10
      timeField: "@timestamp"
      logLevelField: "log.level"
      maxConcurrentShardRequests: 5
      includeFrozen: false
    secureJsonData: # FIXED: ADDED password (REPLACE THIS VALUE)
      basicAuthPassword: "YourSecurePassword123!"
    uid: elasticsearch-ds
    editable: true
