groups:
- name: devsecops.rules
  rules:
  # Application health alerts
  - alert: BackendDown
    expr: up{job="devsecops-backend"} == 0
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: "DevSecOps Backend is down"
      description: "The DevSecOps backend has been down for more than 30 seconds."

  - alert: HighErrorRate
    expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "High error rate detected"
      description: "Error rate is above 10% for {{ $labels.job }}"

  - alert: HighResponseTime
    expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 0.5
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High response time detected"
      description: "95th percentile response time is above 500ms for {{ $labels.job }}"

# ELK Stack alerts
- name: elk.rules
  rules:
  - alert: ElasticsearchDown
    expr: up{job="elasticsearch"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Elasticsearch cluster is down"
      description: "Elasticsearch has been down for more than 1 minute"

  - alert: LogstashDown
    expr: up{job="logstash"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Logstash is down"
      description: "Logstash has been down for more than 1 minute"

  - alert: KibanaDown
    expr: up{job="kibana"} == 0
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "Kibana is down" 
      description: "Kibana has been down for more than 2 minutes"

# Jaeger alerts
- name: jaeger.rules
  rules:
  - alert: JaegerDown
    expr: up{job="jaeger"} == 0
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Jaeger is down"
      description: "Jaeger tracing service has been down for more than 1 minute"
