# Jaeger Configuration for DevSecOps Application
version: "3.8"

services:
  # Jaeger All-in-One
  jaeger:
    image: jaegertracing/all-in-one:1.49
    container_name: devsecops-jaeger
    environment:
      # Collection configuration
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411

      # Storage configuration
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - ES_INDEX_PREFIX=jaeger
      - ES_USERNAME=
      - ES_PASSWORD=

      # Query configuration
      - QUERY_BASE_PATH=/
      - QUERY_LOG_LEVEL=info

      # Sampling configuration
      - SAMPLING_STRATEGIES_FILE=/etc/jaeger/sampling_strategies.json

      # Metrics configuration
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus:9090

      # UI configuration
      - JAEGER_DISABLED=false
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    volumes:
      - ./jaeger-config.json:/etc/jaeger/sampling_strategies.json:ro
    ports:
      # Agent ports
      - "6831:6831/udp"  # Jaeger agent Thrift compact
      - "6832:6832/udp"  # Jaeger agent Thrift binary
      - "5778:5778"      # Agent configuration HTTP

      # Collector ports
      - "14268:14268"    # Jaeger collector HTTP
      - "14250:14250"    # Jaeger collector gRPC
      - "9411:9411"      # Zipkin collector HTTP

      # Query/UI port
      - "16686:16686"    # Jaeger UI

      # Internal ports
      - "14269:14269"    # Admin HTTP
    networks:
      - jaeger-network
      - elk-network
    depends_on:
      - elasticsearch
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:14269 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

networks:
  jaeger-network:
    driver: bridge
  elk-network:
    external: true

volumes:
  jaeger_data:
    driver: local
